# Site settings
title: Noob Studio
header-img: img/home2.jpeg
email: freeweed.m@gmail.com
copyright_name: Noob Studios
description: "บล๊อคเก็บรวบรวมความรู้ ประสบการณ์ เทคนิคและผลงานต่างๆอาธิ Javascript, Java, PHP, Linux, Open Source"
baseurl: ""
url: "noob-studio.github.io"
github_username:  noob-studio
facebook_username:  allstar.pajiko
email_username:  freeweed.m@gmail.com
google_tracking_id: UA-93921891-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
future: true
gems: [jekyll-paginate, jekyll-feed]
